services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}    
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-rpg
    depends_on:
    - mssql
    environment:
        - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}      
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080 
    ports:
      - "8080:8080"

volumes:
  sqlvolume:
    driver: local