services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!2025  
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Passw0rd!2025", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-rpg
    depends_on:
        mssql:
            condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql,1433; Database=dotnet-rpg; User Id=sa; Password=Passw0rd!2025; TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080 
    ports:
      - "8080:8080"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
        - "8085:8080"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    privileged: true 

volumes:
  sqlvolume:
    driver: local
  jenkins_home:
    driver: local