services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!2025  
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-rpg
    depends_on:
    - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql,1433; Database=dotnet-rpg; User Id=sa; Password=Passw0rd!2025; TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080 
    ports:
      - "8080:8080"

volumes:
  sqlvolume:
    driver: local